<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="Views\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Models\**" />
    <None Remove="Services\**" />
    <None Remove="Views\**" />
    <Page Remove="Models\**" />
    <Page Remove="Services\**" />
    <Page Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

</Project>
